FROM apache/airflow:2.7.1

USER root
RUN apt-get update && \
    apt-get install -y postgresql-client && \
    apt-get clean

USER airflow
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

WORKDIR /opt/airflow
